src/components/Header.tsx

<br>
<br>
close #2
<br>
<br>
- <br>
- <br>
<br>

[desgin/#2] 헤더  퍼블리싱 완료

---

src/App.tsx
src/components/SideBar.tsx

<br>
<br>
close #{이슈넘버}
<br>
design/#5
<br>
- <br>
- <br>
<br>

desgin/#5 사이드바 퍼블리싱 완료

---

src/pages/Login.tsx

<br>
<br>
close #4
<br>
<br>
- <br>
- <br>
<br>

[design]로그인 페이지 퍼블리싱

---

src/components/SideBar.tsx

<br>
<br>
design/#7
<br>
<br>
사이드바 퍼블리싱 완료
- <br>
- <br>
<br>

[Design/#7] 사이드바 퍼블리싱 완료

---

index.html
src/App.tsx
src/components/Card.tsx
src/components/CardLayout.tsx
src/components/Header.tsx
src/pages/Login.tsx
src/pages/Main.tsx
src/styles/GlobalStyle.ts

<br>
<br>
close #10
<br>
<br>
- <br>
- <br>
<br>

[design] 카드 레이아웃 퍼블리싱

---

src/App.tsx
src/Router.tsx
src/components/DetailPosting.tsx
src/components/Header.tsx
src/components/SideBar.tsx
src/pages/Login.tsx
src/pages/Posting.tsx

<br>
<br>
close #11 
<br>
<br>
- <br>
- <br>
<br>

design/#11 제품 상세페이지 퍼블리싱 완료

---

src/App.tsx
src/components/DetailPosting.tsx
src/components/SideBar.tsx
src/pages/Login.tsx
src/pages/Posting.tsx
src/styles/GlobalStyle.ts

<br>
<br>
close #14 
<br>
<br>
- <br>
- <br>
<br>

design/#14 게시물 페이지 퍼블리싱 완료

---

index.html
src/App.tsx
src/components/ReviewCard.tsx

<br>
<br>
close #17
<br>
<br>
- <br>
- <br>
<br>

리뷰 카드 퍼블리싱 완료

---

.eslintrc.cjs
package-lock.json
package.json
src/Router.tsx
src/components/SideBar.tsx
src/components/mypage/Profilepicture.tsx
src/pages/Mypage.tsx
yarn.lock

<br>
<br>
close #16 
<br>
<br>
- <br>
- <br>
<br>

마이페이지 프로필 사진 퍼블리싱 완료

---

index.html
src/components/SideBar.tsx
src/components/mypage/InformationInput.tsx
src/components/mypage/Profilepicture.tsx
src/pages/Mypage.tsx

<br>
<br>
close #21 
<br>
<br>
- <br>
- <br>
<br>

마이페이지 인풋 퍼블리싱 완료

---

index.html
src/Router.tsx
src/components/store/FollowerCard.tsx
src/pages/Store.tsx

<br>
<br>
close #25 
<br>
<br>
- <br>
- <br>
<br>

[design] 팔로워, 팔로잉 컴포넌트 퍼블리싱 완료

---

src/components/CardLayout.tsx
src/components/ReviewCard.tsx
src/components/Tab.tsx
src/pages/Main.tsx

<br>
<br>
close #23
<br>
<br>
- <br>
- <br>
<br>

[design] 탭 퍼블리싱 완료

---

src/apis/getItems/Item.ts
src/components/Card.tsx
src/components/CardLayout.tsx
src/components/MypageCard.tsx
src/components/ReviewCard.tsx
src/components/SideBar.tsx
src/pages/Main.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

[feat] 최신 상품 axios 연결

---

src/apis/getItems/Item.ts
src/apis/sidebar/goods.ts
src/components/SideBar.tsx
src/components/mypage/InformationInput.tsx
src/pages/Mypage.tsx
src/styles/GlobalStyle.ts

<br>
<br>
close #32 
<br>
<br>
- <br>
- <br>
<br>

design 사이드바 패딩 수정 및 axios 연결

---

src/components/common/SideBar.tsx
src/components/layout/DetailPosting.tsx
src/pages/Posting.tsx

<br>
<br>
close #35 
<br>
<br>
- <br>
- <br>
<br>

[design] Posting 페이지 퍼블리싱 완료

---

index.html
src/apis/config.ts
src/apis/header/Header.ts
src/components/common/Header.tsx

<br>
<br>
close #39 
<br>
<br>
- <br>
- <br>
<br>

[feat] 검색 기능 구현 완료

---

package.json
src/App.tsx
src/Router.tsx
src/apis/header/Header.ts
src/apis/login/kakao.ts
src/components/common/Header.tsx
src/components/common/SideBar.tsx
src/components/login/LoginModal.tsx
src/pages/Chat.tsx
src/pages/Main.tsx
src/pages/Redirect.tsx
src/pages/ViewItems.tsx
src/styles/GlobalStyle.ts
src/styles/theme.ts
src/utils/cookie.ts
yarn.lock

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

Feat/#43 로그인 구현

---

index.html
package-lock.json
package.json
src/apis/mypage/members.ts
src/components/mypage/InformationInput.tsx
src/pages/Mypage.tsx
tsconfig.json
yarn.lock

<br>
<br>
<br>
<br>
- <br>
- <br>
<br>

위치 정보 수정기능 구현

---

src/apis/follow/follow.ts
src/apis/getItems/Item.ts
src/apis/header/Header.ts
src/apis/mypage/members.ts
src/apis/shop/shop.ts
src/components/common/SideBar.tsx
src/components/common/Tab.tsx
src/components/layout/FollowLayout.tsx
src/components/layout/ReviewLayout.tsx
src/components/layout/TabCardLayout.tsx
src/components/store/FollowerCard.tsx
src/components/store/ReviewCard.tsx
src/pages/Main.tsx
src/pages/Posting.tsx
src/pages/Store.tsx
src/pages/ViewItems.tsx

<br>
<br>
close #51
<br>
<br>
- <br>
- <br>
<br>

[feat] 상점 페이지 axios 연결

---

src/Router.tsx
src/apis/mypage/members.ts
src/components/common/Header.tsx
src/components/layout/CardLayout.tsx
src/pages/SignUp.tsx

<br>
<br>
close #54 
<br>
<br>
- <br>
- <br>
<br>

회원가입 axios 연결

---

package.json
src/pages/Chat.tsx
yarn.lock

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

[design] 채팅페이지 퍼블리싱

---

src/Router.tsx
src/components/common/Header.tsx
src/components/common/SideBar.tsx
src/pages/Redirect.tsx
src/pages/ViewItems.tsx
src/styles/theme.ts

<br>
<br>
close #61 
<br>
<br>
- <br>
- <br>
<br>

[BugFix] 검색, 카테고리 오류 해결

---

src/apis/login/kakao.ts
src/apis/mypage/members.ts
src/components/common/Card.tsx
src/components/common/Header.tsx
src/components/common/SideBar.tsx
src/components/layout/CardLayout.tsx
src/pages/Store.tsx
src/styles/GlobalStyle.ts
src/styles/theme.ts

<br>
<br>
close #72 
<br>
<br>
- <br>
- <br>
<br>

[design/#72]헤더, 사이드바 css 수정 완료

---

src/components/common/Modal.tsx
src/components/register/Category.tsx
src/components/register/Image.tsx
src/hooks/useInput.ts
src/pages/Register.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

[feat] 상품 등록 -ing

---

src/App.tsx
src/apis/getItems/Item.ts
src/components/common/Card.tsx
src/components/common/ScrollToTop.tsx
src/pages/Mypage.tsx
src/pages/ViewItems.tsx

<br>
<br>
close #75 
<br>
<br>
- <br>
- <br>
<br>

[feat/#75] 무한스크롤 구현

---

src/apis/login/kakao.ts
src/apis/posting/posting.ts
src/components/common/DropBar.tsx
src/components/common/Header.tsx
src/components/common/Tab.tsx
src/components/layout/CardLayout.tsx
src/components/layout/DetailPosting.tsx
src/components/layout/ReviewLayout.tsx
src/components/register/Category.tsx
src/components/register/Image.tsx
src/components/store/ReviewCard.tsx
src/hooks/useInput.ts
src/pages/Mypage.tsx
src/pages/Register.tsx
src/pages/Store.tsx
src/pages/ViewItems.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

[feat] 상품 수정

---

src/Router.tsx
src/apis/login/kakao.ts
src/apis/posting/posting.ts
src/components/common/DropBar.tsx
src/components/common/Header.tsx
src/components/layout/DetailPosting.tsx
src/components/mypage/Profilepicture.tsx
src/components/register/Image.tsx
src/hooks/useInput.ts
src/pages/Register.tsx

<br>
<br>
close #84 
<br>
<br>
- <br>
- <br>
<br>

[BugFix] 상품 등록

---

src/apis/config.ts
src/apis/header/Header.ts
src/apis/login/kakao.ts
src/apis/posting/posting.ts
src/apis/shop/shop.ts
src/components/common/DropBar.tsx
src/components/common/Tab.tsx
src/components/layout/CardLayout.tsx
src/components/layout/DetailPosting.tsx
src/components/layout/FollowLayout.tsx
src/components/layout/ReviewLayout.tsx
src/hooks/useInput.ts
src/pages/Chat.tsx
src/pages/Info.tsx
src/pages/Main.tsx
src/pages/Redirect.tsx
src/pages/Register.tsx
src/pages/Store.tsx

<br>
<br>
close #88 
<br>
<br>
- <br>
- <br>
<br>

[BugFix] 타입 수정

---

src/apis/config.ts
src/apis/getItems/Item.ts
src/apis/posting/posting.ts
src/components/common/SideBar.tsx
src/components/layout/DetailPosting.tsx
src/hooks/useInput.ts
src/pages/Redirect.tsx
src/pages/Register.tsx
src/pages/Store.tsx
src/pages/ViewItems.tsx

<br>
<br>
close #95
<br>
<br>
- <br>
- <br>
<br>

Bug fix/#95

---

src/Router.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

[refactor]코드스플리팅

---

src/App.tsx
src/Main.tsx
src/Router.tsx
src/apis/config.ts
src/components/chat/FirstChat.tsx
src/components/login/LoginModal.tsx
src/pages/Chat.tsx
src/pages/NotFound.tsx

<br>
<br>
close #110 
<br>
<br>
- <br>
- <br>
<br>

[design] 에러 페이지 퍼블리싱 완료

---

src/components/common/Card.tsx
src/components/common/Tab.tsx
src/components/layout/CardLayout.tsx
src/components/layout/FollowLayout.tsx
src/components/layout/ReviewLayout.tsx
src/components/layout/TabLayout.tsx
src/pages/Mypage.tsx
src/pages/Welcome.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

[design] 탭 디자인

---

src/apis/posting/posting.ts
src/components/common/DropBar.tsx
src/components/layout/CardLayout.tsx
src/components/layout/DetailPosting.tsx
src/pages/Store.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

[feat]상품 삭제

---

src/components/common/Card.tsx
src/components/layout/CardLayout.tsx
src/components/layout/DetailPosting.tsx
src/components/mypage/ReviewModal.tsx
src/pages/Store.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

[bugfix] 새로고침 에러 및 상점 소개 수정

---

src/assets/svgs/UploadSvg.tsx
src/pages/Chat.tsx
src/pages/Welcome.tsx

<br>
<br>
close #151 
<br>
<br>
- <br>
- <br>
<br>

[feat] 채팅 시 한 번에 페이지 이동

---

src/apis/chat/chat.ts
src/assets/svgs/FirstChatSvg.tsx
src/components/chat/FirstChat.tsx
src/components/layout/RecommendLayout.tsx
src/pages/Chat.tsx
src/pages/Register.tsx

<br>
<br>
close #151 
<br>
<br>
- <br>
- <br>
<br>

[feat] 채팅방 수정

---

src/apis/getItems/Item.ts
src/components/layout/CardLayout.tsx
src/pages/Home.tsx
src/pages/ViewItems.tsx

<br>
<br>
close #157 
<br>
<br>
- <br>
- <br>
<br>

[feat] 인기상품 토글

---

src/components/chat/ChatBox.tsx
src/components/mypage/Profilepicture.tsx
src/pages/Chat.tsx
src/pages/ViewItems.tsx

<br>
<br>
close #159 
<br>
<br>
- <br>
- <br>
<br>

[feat] 나가기 구현
